# Generated by Django 4.2.7 on 2023-11-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_menu_inventory_remove_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='inventory',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
