# Generated by Django 4.2.7 on 2023-11-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menu_inventory_menu_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_guests',
            new_name='reservation_slot',
        ),
    ]
